In [2]:
import numpy as np

In [ ]:
arr = np.array(10)
arr2 = np.array([1, 2, 3, 4, 5])
arr3 = np.array([[1, 2, 3], [4, 5, 6]])
arr4 = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr.ndim, arr.shape)
print(arr2.ndim, arr2.shape)
print(arr3.ndim, arr3.shape)
print(arr4.ndim, arr4.shape)

In [3]:
# Crear matriz de nxm con 0 elementos
arr5 = np.zeros((3, 2))
print(arr5)

arr6 = np.arange(10, 50)
print(arr6)
arr6 = arr6.reshape(4, 10)
print(arr6)

[[0. 0.]
 [0. 0.]
 [0. 0.]]
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
[[10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]]


# Producto punto

In [4]:
a = np.array([1,2,3])
b = np.array([4,5,6])

elemento = a*b
dot_product = np.dot(a, b)
dot_product_alt = a @ b
print(elemento)
print(dot_product)
print(dot_product_alt)

[ 4 10 18]
32
32


# Producto escalar

In [5]:
A = np.array([[1, 2], [3,4]])
B = np.array([[5,6], [7,8]])

elementomatrix = A*B
matrix_product = np.dot(A, B)
matrix_product_alt = A @ B

print(elementomatrix)
print(matrix_product)
print(matrix_product_alt)

[[ 5 12]
 [21 32]]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [13]:
A = np.array([[1, 2, 3], [2, 3, 4], [3,4,5]])
B = np.array([[5,6], [9,11], [15,18]])
C = np.array([4,5,6])

print(np.dot(A, B))
B = np.reshape(B, (2,3))
print(np.dot(B, A))
print(np.dot(A,C))
print(np.dot(B,C))

[[ 68  82]
 [ 97 117]
 [126 152]]
[[ 44  64  84]
 [ 95 139 183]]
[32 47 62]
[104 227]


ValueError: shapes (3,3) and (2,) not aligned: 3 (dim 1) != 2 (dim 0)